class_name TrackBuilder
extends RefCounted
## Turns a TrackSpec into a playable scene tree.
##
## The road is generated by walking the centreline and offsetting left and
## right by half the width. Everything else — walls, checkpoints, surface
## patches, jumps and the start grid — hangs off that same walk, so the pieces
## can never drift out of alignment with each other.

## How finely the centreline is sampled, in pixels. Smaller is smoother and
## more expensive; this is fine for a road a few kilometres long.
const SAMPLE_STEP := 24.0
## Walls sit slightly outside the visible road edge so a car that clips the
## verge scrubs speed before it hits anything solid.
const WALL_MARGIN := 1.2

const ROAD_COLOR_TARMAC := Color(0.18, 0.18, 0.20)
const ROAD_COLOR_DIRT := Color(0.35, 0.26, 0.17)
const ROAD_COLOR_GRAVEL := Color(0.42, 0.39, 0.34)
const ROAD_COLOR_SNOW := Color(0.86, 0.88, 0.92)
const ROAD_COLOR_ICE := Color(0.72, 0.82, 0.88)
const ROAD_COLOR_GRASS := Color(0.22, 0.35, 0.18)
const ROAD_COLOR_MUD := Color(0.28, 0.22, 0.14)

var spec: TrackSpec
var curve: Curve2D
var _samples: Array[Dictionary] = []   # [{ pos, dir, normal, offset, waypoint }]

## Filled in by build(); the race director reads these.
var checkpoints: Array[Checkpoint] = []
var start_grid: Array[Transform2D] = []
var total_length_px: float = 0.0


func _init(p_spec: TrackSpec) -> void:
	spec = p_spec
	curve = spec.build_curve()


func build() -> Node2D:
	var root := Node2D.new()
	root.name = "Track_%s" % spec.id

	if curve.point_count < 2:
		push_error("TrackBuilder: track '%s' has too few waypoints" % spec.id)
		return root

	_walk_centreline()

	root.add_child(_build_ground())
	root.add_child(_build_road())
	root.add_child(_build_scenery())
	root.add_child(_build_surface_zones())
	root.add_child(_build_walls())
	root.add_child(_build_checkpoints())
	root.add_child(_build_ramps())
	root.add_child(_build_props())
	_build_start_grid()
	return root


# --- Centreline -------------------------------------------------------------

func _walk_centreline() -> void:
	_samples.clear()
	total_length_px = curve.get_baked_length()
	var offset := 0.0
	while offset < total_length_px:
		var pos := curve.sample_baked(offset)
		# Finite-difference tangent: cheaper than baked tangents and stable
		# enough at this sample spacing.
		var ahead := curve.sample_baked(minf(offset + 4.0, total_length_px))
		var dir := (ahead - pos).normalized()
		if dir == Vector2.ZERO:
			dir = Vector2.RIGHT
		_samples.append({
			"pos": pos,
			"dir": dir,
			"normal": Vector2(-dir.y, dir.x),
			"offset": offset,
			"waypoint": _nearest_waypoint_index(offset),
		})
		offset += SAMPLE_STEP

	if spec.closed and _samples.size() > 2:
		_samples.append(_samples[0].duplicate())


func _nearest_waypoint_index(offset: float) -> int:
	var n := spec.waypoints.size()
	if n == 0 or total_length_px <= 0.0:
		return 0
	var frac := offset / total_length_px
	return clampi(int(frac * n), 0, n - 1)


func _half_width_px() -> float:
	return spec.width * 0.5 * GameConfig.PIXELS_PER_METRE


func _edge_points(side: float, extra: float = 0.0) -> PackedVector2Array:
	var out := PackedVector2Array()
	var half := _half_width_px() + extra
	for s in _samples:
		out.append(s["pos"] + s["normal"] * half * side)
	return out


# --- Visuals ----------------------------------------------------------------

## Verges, surface wear, marker posts and whatever grows beside the road.
func _build_scenery() -> Node2D:
	var scenery := TrackScenery.new()
	scenery.name = "Scenery"
	# Above the ground, the road and the surface patches, below the cars.
	scenery.z_index = -7
	scenery.build(spec, _samples, _half_width_px())
	return scenery


func _build_ground() -> Node2D:
	# A big backdrop so the world is not void-black outside the road.
	var ground := Polygon2D.new()
	ground.name = "Ground"
	var bounds := _bounds().grow(2000.0)
	ground.polygon = PackedVector2Array([
		bounds.position,
		Vector2(bounds.end.x, bounds.position.y),
		bounds.end,
		Vector2(bounds.position.x, bounds.end.y),
	])
	var surround: Dictionary = TrackScenery.SURROUND.get(
		spec.default_surface, TrackScenery.SURROUND[TireModel.Surface.GRAVEL])
	ground.color = surround["ground"]
	ground.z_index = -20
	return ground


func _build_road() -> Node2D:
	var holder := Node2D.new()
	holder.name = "Road"
	holder.z_index = -10

	var left := _edge_points(-1.0)
	var right := _edge_points(1.0)
	right.reverse()

	var road := Polygon2D.new()
	road.name = "Surface"
	var poly := PackedVector2Array(left)
	poly.append_array(right)
	road.polygon = poly
	road.color = _surface_color(spec.default_surface)
	holder.add_child(road)

	# Edge lines make the road readable at the zoom a top-down camera uses.
	for side in [-1.0, 1.0]:
		var line := Line2D.new()
		line.points = _edge_points(side)
		line.width = 3.0
		line.default_color = Color(1, 1, 1, 0.25)
		line.closed = spec.closed
		holder.add_child(line)
	return holder


## Public so scenery can tint its wear to the road it is drawn on.
static func surface_colour(s: TireModel.Surface) -> Color:
	match s:
		TireModel.Surface.TARMAC: return ROAD_COLOR_TARMAC
		TireModel.Surface.DIRT: return ROAD_COLOR_DIRT
		TireModel.Surface.GRAVEL: return ROAD_COLOR_GRAVEL
		TireModel.Surface.SNOW: return ROAD_COLOR_SNOW
		TireModel.Surface.ICE: return ROAD_COLOR_ICE
		TireModel.Surface.MUD: return ROAD_COLOR_MUD
		_: return ROAD_COLOR_GRASS


func _surface_color(s: TireModel.Surface) -> Color:
	match s:
		TireModel.Surface.TARMAC: return ROAD_COLOR_TARMAC
		TireModel.Surface.DIRT: return ROAD_COLOR_DIRT
		TireModel.Surface.GRAVEL: return ROAD_COLOR_GRAVEL
		TireModel.Surface.SNOW: return ROAD_COLOR_SNOW
		TireModel.Surface.ICE: return ROAD_COLOR_ICE
		TireModel.Surface.MUD: return ROAD_COLOR_MUD
		_: return ROAD_COLOR_GRASS


# --- Surfaces ---------------------------------------------------------------

func _build_surface_zones() -> Node2D:
	var holder := Node2D.new()
	holder.name = "Surfaces"

	# The whole road gets a zone for the default surface, then override
	# stretches are layered on top. Cars push/pop as they cross the boundaries.
	holder.add_child(_make_surface_zone(0, _samples.size() - 1, spec.default_surface, -9))

	for override in spec.surface_overrides:
		var from_wp := int(override["from"])
		var to_wp := int(override["to"])
		var range_start := -1
		var range_end := -1
		for i in _samples.size():
			var wp := int(_samples[i]["waypoint"])
			if wp >= from_wp and wp <= to_wp:
				if range_start < 0:
					range_start = i
				range_end = i
		if range_start >= 0 and range_end > range_start:
			holder.add_child(_make_surface_zone(range_start, range_end, override["surface"], -8))
	return holder


func _make_surface_zone(from_i: int, to_i: int, surf: TireModel.Surface, z: int) -> SurfaceZone:
	var zone := SurfaceZone.new()
	zone.surface = surf
	zone.name = "Surface_%d_%d" % [from_i, to_i]

	var half := _half_width_px()
	var poly := PackedVector2Array()
	for i in range(from_i, to_i + 1):
		poly.append(_samples[i]["pos"] + _samples[i]["normal"] * half * -1.0)
	for i in range(to_i, from_i - 1, -1):
		poly.append(_samples[i]["pos"] + _samples[i]["normal"] * half)

	var shape := CollisionPolygon2D.new()
	shape.polygon = poly
	zone.add_child(shape)

	# Overrides get a visible patch so the player can read the surface change.
	if z == -8:
		var visual := Polygon2D.new()
		visual.polygon = poly
		visual.color = _surface_color(surf)
		visual.z_index = z
		zone.add_child(visual)
	return zone


# --- Walls ------------------------------------------------------------------

func _build_walls() -> StaticBody2D:
	var body := StaticBody2D.new()
	body.name = "Walls"
	body.collision_layer = 1
	body.collision_mask = 0

	var margin := WALL_MARGIN * GameConfig.PIXELS_PER_METRE
	for side in [-1.0, 1.0]:
		var pts := _edge_points(side, margin)
		var shape := CollisionShape2D.new()
		shape.shape = _barrier_shape(pts)
		body.add_child(shape)

		var barrier := Line2D.new()
		barrier.points = pts
		barrier.width = 5.0
		barrier.default_color = Color(0.75, 0.15, 0.12, 0.9)
		barrier.closed = spec.closed
		body.add_child(barrier)
	return body


## An open guardrail along a polyline.
##
## Built from explicit segment pairs rather than a CollisionPolygon2D in
## BUILD_SEGMENTS mode, because that mode always joins the last point back to
## the first. On a point-to-point stage that put a barrier straight across the
## map from the finish to the start line — invisible, and directly in front of
## the grid.
func _barrier_shape(points: PackedVector2Array) -> ConcavePolygonShape2D:
	var segments := PackedVector2Array()
	for i in range(points.size() - 1):
		segments.append(points[i])
		segments.append(points[i + 1])
	if spec.closed and points.size() > 1:
		segments.append(points[points.size() - 1])
		segments.append(points[0])
	var shape := ConcavePolygonShape2D.new()
	shape.segments = segments
	return shape


# --- Checkpoints ------------------------------------------------------------

func _build_checkpoints() -> Node2D:
	var holder := Node2D.new()
	holder.name = "Checkpoints"
	checkpoints.clear()

	var spacing_px := spec.checkpoint_spacing * GameConfig.PIXELS_PER_METRE
	var count := maxi(int(total_length_px / maxf(spacing_px, 1.0)), 2)
	var step := total_length_px / float(count)

	for i in count:
		var offset := step * float(i)
		var sample := _sample_at(offset)
		var cp := Checkpoint.new()
		cp.index = i
		# On a closed track, checkpoint 0 sits on the start/finish line.
		cp.is_finish = (i == 0)
		cp.name = "Checkpoint_%d" % i
		cp.position = sample["pos"]
		cp.rotation = sample["dir"].angle()

		var shape := CollisionShape2D.new()
		var rect := RectangleShape2D.new()
		rect.size = Vector2(18.0, _half_width_px() * 2.2)
		shape.shape = rect
		cp.add_child(shape)

		if cp.is_finish:
			var marker := Line2D.new()
			marker.points = PackedVector2Array([
				Vector2(0, -_half_width_px()), Vector2(0, _half_width_px())])
			marker.width = 6.0
			marker.default_color = Color(1, 1, 1, 0.8)
			cp.add_child(marker)

		holder.add_child(cp)
		checkpoints.append(cp)
	return holder


# --- Ramps ------------------------------------------------------------------

## Hazards a track places on its own racing surface. Unlike scenery, these are
## real bodies with real consequences, so they are placed deliberately in
## tracks.json rather than scattered.
func _build_props() -> Node2D:
	var root := Node2D.new()
	root.name = "Props"
	root.z_index = -1
	for entry in spec.props:
		var prop := TrackProp.by_id(String(entry["prop"]))
		if prop == null:
			push_warning("Track '%s' places unknown prop '%s'" % [spec.id, entry["prop"]])
			continue
		var index := clampi(int(entry["at"]), 0, spec.waypoints.size() - 1)
		var sample := _sample_at_waypoint(index)
		var along: float = float(entry["along"]) * GameConfig.PIXELS_PER_METRE
		var across: float = clampf(float(entry["side"]), -1.0, 1.0) * _half_width_px() * 0.82
		var position: Vector2 = sample["pos"] + sample["dir"] * along \
			+ sample["normal"] * across
		var angle: float = sample["dir"].angle()
		root.add_child(PropInstance.create(prop, position, angle, 1.0,
			hash(spec.id) + index))
	return root


func _build_ramps() -> Node2D:
	var holder := Node2D.new()
	holder.name = "Ramps"
	var ppm := GameConfig.PIXELS_PER_METRE

	for r in spec.ramps:
		var wp := int(r["at"])
		var sample := _sample_at_waypoint(wp)
		if sample.is_empty():
			continue
		var ramp := Ramp.new()
		ramp.name = "Ramp_%d" % wp
		ramp.launch_speed = float(r["launch"])
		ramp.position = sample["pos"]
		ramp.rotation = sample["dir"].angle()

		var length_px := float(r["length"]) * ppm
		var shape := CollisionShape2D.new()
		var rect := RectangleShape2D.new()
		rect.size = Vector2(length_px, _half_width_px() * 2.0)
		shape.shape = rect
		ramp.add_child(shape)

		var visual := Polygon2D.new()
		visual.polygon = PackedVector2Array([
			Vector2(-length_px * 0.5, -_half_width_px()),
			Vector2(length_px * 0.5, -_half_width_px()),
			Vector2(length_px * 0.5, _half_width_px()),
			Vector2(-length_px * 0.5, _half_width_px()),
		])
		visual.color = Color(0.85, 0.68, 0.20, 0.55)
		visual.z_index = -5
		ramp.add_child(visual)

		holder.add_child(ramp)
	return holder


# --- Start grid -------------------------------------------------------------

func _build_start_grid() -> void:
	start_grid.clear()
	var ppm := GameConfig.PIXELS_PER_METRE
	# Two columns, staggered, like a rally start.
	var row_spacing := 7.0 * ppm
	var column_offset := 3.0 * ppm

	for i in GameConfig.MAX_NET_PLAYERS:
		var row := i / 2
		var column := 1 if (i % 2) == 0 else -1
		var offset: float
		if spec.closed:
			# Sit behind the start/finish line, which is measured at the very
			# end of the lap, so the first gate is ahead rather than passed.
			offset = total_length_px - row_spacing * float(row + 1)
			offset = fposmod(offset, maxf(total_length_px, 1.0))
		else:
			# A point-to-point stage has no lap to be behind: the grid forms up
			# at the beginning of the road and runs forward from there.
			offset = row_spacing * float(row)
		var sample := _sample_at(offset)
		var pos: Vector2 = sample["pos"] + sample["normal"] * column_offset * float(column)
		start_grid.append(Transform2D(sample["dir"].angle(), pos))


# --- Sampling helpers -------------------------------------------------------

func _sample_at(offset: float) -> Dictionary:
	var pos := curve.sample_baked(offset)
	var ahead := curve.sample_baked(fposmod(offset + 4.0, maxf(total_length_px, 1.0)))
	var dir := (ahead - pos).normalized()
	if dir == Vector2.ZERO:
		dir = Vector2.RIGHT
	return {"pos": pos, "dir": dir, "normal": Vector2(-dir.y, dir.x)}


func _sample_at_waypoint(index: int) -> Dictionary:
	for s in _samples:
		if int(s["waypoint"]) == index:
			return s
	return {}


func _bounds() -> Rect2:
	if _samples.is_empty():
		return Rect2()
	var rect := Rect2(_samples[0]["pos"], Vector2.ZERO)
	for s in _samples:
		rect = rect.expand(s["pos"])
	return rect


## What the road is made of at a given distance along it. Lets a driver plan
## for the ice patch it is about to reach rather than only for the tarmac it is
## currently standing on.
func surface_at_offset(offset_px: float) -> TireModel.Surface:
	if _samples.is_empty():
		return spec.default_surface
	var length := maxf(total_length_px, 1.0)
	var target := fposmod(offset_px, length) if spec.closed else clampf(offset_px, 0.0, length)
	var index := clampi(int(target / SAMPLE_STEP), 0, _samples.size() - 1)
	return spec.surface_at_waypoint(int(_samples[index]["waypoint"]))


## Distance along the centreline for an arbitrary world position. The race
## director uses this to order the field.
func progress_at(world_pos: Vector2) -> float:
	var best := 0.0
	var best_dist := INF
	for s in _samples:
		var d: float = world_pos.distance_squared_to(s["pos"])
		if d < best_dist:
			best_dist = d
			best = s["offset"]
	return best
